### ISSUE TITLE
BarnBridge Project Call 19 Agenda

### ISSUE THREAD

**Issue by DannyDesert** [BarnBridge/BarnBridge-PM#33]
## **BarnBridge Project Call 019 Agenda**

**Meeting Date/Time:** Thursday 2021/6/10 at 15:00 UTC
**Meeting Duration:** 30 mins - 1 hour
**Breakdown:** 
- Tech/Dev: 30 mins 
- Roundtable: 30 mins

## **Agenda**
- Intro Christian

### **Tech/Dev**
- almost done with SE
- almost done with Matic SY
- almost done with Gnosis Safe app support
- almost done with SY idle integration
- started work on SA smart contracts
- secret project that compliments SY

### **Operations**
- Vitali
  - social media banners design revamp
  - discord bot faq update (releasing dtoday)
  - some of the marketing stuff
  - mention that defi safety score update is WIP
  
- Max
  - Bancor Snapshot #2
  - AAVE v2 Signaling
  - Nexus Mutual Update
  - Rari Capital Consideration
  - Quantstamp Article
  - Treasury Framework 

### **Round Table**

**Comment by mike9870** [comment]
How will the matic tokens be claimed in the Aave/Poloygon market? Embedded in the spot yield or claimed separately?
